package codice;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author matge
 */
public class PnlMenu extends javax.swing.JPanel {

    private FrmHome frame;
    public Font font = new java.awt.Font("Montserrat Bold", java.awt.Font.PLAIN, 24);
    /**
     * Creates new form PnlMenu
     */
    public PnlMenu() {
        initComponents();
        
    }
    
    public void disegnaComboBox(ColorMode tema)
    {
        Color backColor;
        Color textColor;
        if(tema == ColorMode.SCURO)
        {
            backColor = PaletteColori.NERO; 
            textColor = PaletteColori.BIANCO;
        }
        else
        {
            backColor = PaletteColori.BIANCO;
            textColor = PaletteColori.NERO;
        }
        Color c2 = frame.coloreSecondario;
        
        jComboBox1.setFont(font);
        jComboBox1.setBackground(backColor);
        jComboBox1.setForeground(textColor);
        jComboBox1.setFocusable(false);
        jComboBox1.setOpaque(false);
        
        jComboBox1.setRenderer(new DefaultListCellRenderer()    //Modifica il Renderer della tendina che si apre nella Combobox
            {
                @Override
                public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                    JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    label.setBorder(BorderFactory.createEmptyBorder(10, 15, 10, 15));       //Bordo
                    label.setFont(font);
                    label.setHorizontalAlignment(SwingConstants.CENTER);
                    if (isSelected)     //Colora l'opzione selezionata
                    {       
                        label.setForeground(c2);    //Testo in colore secondario
                        label.setBackground(backColor);
                    } 
                    else 
                    {
                        // Colore normale
                        label.setBackground(backColor);
                        label.setForeground(textColor);
                    }
                    return label;
                }      
            }
        );
        
        jComboBox1.setUI(new javax.swing.plaf.basic.BasicComboBoxUI()       
            {
                @Override
                protected JButton createArrowButton()   //Modifica il bottone contenente la freccia della Combobox
                {
                    JButton flatButton = new JButton("▼"); 
                    flatButton.setBorder(BorderFactory.createEmptyBorder(0, 5, 0, 5));
                    flatButton.setContentAreaFilled(false);
                    flatButton.setFocusPainted(false);
                    flatButton.setOpaque(false);
                    flatButton.setBackground(backColor);
                    flatButton.setForeground(textColor);
                    return flatButton;
                }

                @Override
                public void paintCurrentValueBackground(Graphics g, Rectangle bounds, boolean hasFocus) {
                    //Sovrascrivo il metodo vuoto per impedire il disegno di un rettangolo grigio di base
                    //che si mostrerebbe come bordo nel design attuale
                }              
            }
        );
    }
    public void setLabelsColor(Color c)
    {
        jLabel1.setForeground(c);
        jLabel3.setForeground(c);
        jLabel4.setForeground(c);
        jLabel5.setForeground(c);
        jLabel6.setForeground(c);
        jLabel7.setForeground(c);
    }
    
    public void setFrame(FrmHome frame)
    {
        this.frame = frame;
    }
    
    public void setFont()
    {
        jLabel1.setFont(font);
        jLabel3.setFont(font);
        jLabel4.setFont(font);
        jLabel5.setFont(font);
        jLabel6.setFont(font);
        jLabel7.setFont(font);
    }
    // Sostituisci "jComboBox1" con il nome della variabile della tua combobox

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(14, 17, 17));
        setMaximumSize(new java.awt.Dimension(200, 700));
        setMinimumSize(new java.awt.Dimension(200, 700));
        setPreferredSize(new java.awt.Dimension(200, 700));

        jLabel1.setBackground(new java.awt.Color(14, 17, 17));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCURO");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 75));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        add(jLabel1);

        jSeparator1.setMaximumSize(new java.awt.Dimension(100, 10));
        jSeparator1.setMinimumSize(new java.awt.Dimension(100, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 5));
        add(jSeparator1);

        jPanel1.setMaximumSize(new java.awt.Dimension(200, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 0));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 75));

        jComboBox1.setBackground(new java.awt.Color(255, 0, 51));
        jComboBox1.setForeground(PaletteColori.NERO);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEMA", "VERDE", "ROSSO", "BLU" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jComboBox1.setFocusable(false);
        jComboBox1.setPreferredSize(new java.awt.Dimension(175, 70));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);

        add(jPanel1);

        jSeparator2.setMaximumSize(new java.awt.Dimension(100, 10));
        jSeparator2.setMinimumSize(new java.awt.Dimension(100, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(100, 5));
        add(jSeparator2);

        jLabel3.setBackground(new java.awt.Color(14, 17, 17));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VOCI");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 75));
        add(jLabel3);

        jSeparator3.setMaximumSize(new java.awt.Dimension(100, 10));
        jSeparator3.setMinimumSize(new java.awt.Dimension(100, 0));
        jSeparator3.setPreferredSize(new java.awt.Dimension(100, 5));
        add(jSeparator3);

        jLabel4.setBackground(new java.awt.Color(14, 17, 17));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("VOCI");
        jLabel4.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 75));
        add(jLabel4);

        jSeparator4.setMaximumSize(new java.awt.Dimension(100, 10));
        jSeparator4.setMinimumSize(new java.awt.Dimension(100, 0));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 5));
        add(jSeparator4);

        jLabel5.setBackground(new java.awt.Color(14, 17, 17));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("VOCI");
        jLabel5.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel5.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 75));
        add(jLabel5);

        jSeparator5.setMaximumSize(new java.awt.Dimension(100, 10));
        jSeparator5.setMinimumSize(new java.awt.Dimension(100, 0));
        jSeparator5.setPreferredSize(new java.awt.Dimension(100, 5));
        add(jSeparator5);

        jLabel7.setBackground(new java.awt.Color(14, 17, 17));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel7.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 75));
        add(jLabel7);

        jLabel6.setBackground(new java.awt.Color(14, 17, 17));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel6.setMinimumSize(new java.awt.Dimension(200, 0));
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 100));
        add(jLabel6);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        frame.setTema();
        if(frame.getTema() == ColorMode.SCURO)
        {
            jLabel1.setText("CHIARO"); 
            jLabel1.setBackground(PaletteColori.NERO);
        }
        else
        {
            jLabel1.setText("SCURO");
            jLabel1.setBackground(PaletteColori.BIANCO);
        }
        frame.colorMode();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(frame.coloreSecondario);       
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        if(frame.getTema() == ColorMode.SCURO)
        {
            jLabel1.setForeground(PaletteColori.BIANCO);
        }
        else
        {
            jLabel1.setForeground(PaletteColori.NERO);
        }
    }//GEN-LAST:event_jLabel1MouseExited

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        jComboBox1.setForeground(frame.coloreSecondario);
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        if(frame.getTema() == ColorMode.SCURO)
        {
            jComboBox1.setForeground(PaletteColori.BIANCO);
        }
        else
        {
            jComboBox1.setForeground(PaletteColori.NERO);
        }
    }//GEN-LAST:event_jComboBox1MouseExited

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Object sceltaTema = jComboBox1.getSelectedItem();
        String colore = sceltaTema.toString();
        
        switch(colore)
        {
            case "BLU":
                frame.coloreSecondario = PaletteColori.BLU;
                break;
            case "VERDE":
                frame.coloreSecondario = PaletteColori.VERDE;
                break;
            default:
                frame.coloreSecondario = PaletteColori.VERDE;
                break;
        }
        frame.colorMode();
        frame.repaint();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
