/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codice;

import java.awt.Font;

/**
 *
 * @author matge
 */
public class PnlTransazione extends componenti.RoundPanel {
    public Font font = new java.awt.Font("Montserrat Bold", java.awt.Font.PLAIN, 24);
    /**
     * Creates new form PnlTransazione
     */
    public PnlTransazione() {
        initComponents();
        this.setRaggio(50);
        this.setBackground(componenti.PaletteColori.BIANCO);
        
        
        //FONT LABEL
        LblNome.setFont(new java.awt.Font("Montserrat Semibold", java.awt.Font.PLAIN, 18));          
        LblData.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 14)); 
        LblAmmonto.setFont(new java.awt.Font("Montserrat Semibold", java.awt.Font.PLAIN, 18));    
        LblTipo.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 14));
        
        
        LblNome.setText("Nome pagamento");
        LblData.setText("12 apr 2026");
        LblAmmonto.setText("10.99€");
        LblTipo.setText("pagamento/entrata");
        

    }
    
    public void setColorMode(ColorMode c)
    {
        if(c == ColorMode.CHIARO)
        {
            this.setBackground(componenti.PaletteColori.BIANCO);
            this.setColoreBordo(componenti.PaletteColori.BIANCO);
            
            LblAmmonto.setForeground(componenti.PaletteColori.NERO);
            LblData.setForeground(componenti.PaletteColori.NERO);
            LblNome.setForeground(componenti.PaletteColori.NERO);
            LblTipo.setForeground(componenti.PaletteColori.NERO); 
        }
        else
        {
            this.setBackground(componenti.PaletteColori.NERO);
            this.setColoreBordo(componenti.PaletteColori.NERO);
            
            LblAmmonto.setForeground(componenti.PaletteColori.BIANCO);
            LblData.setForeground(componenti.PaletteColori.BIANCO);
            LblNome.setForeground(componenti.PaletteColori.BIANCO);
            LblTipo.setForeground(componenti.PaletteColori.BIANCO); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        LblAmmonto = new javax.swing.JLabel();
        LblData = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblTipo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 100));
        setMinimumSize(new java.awt.Dimension(350, 100));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        LblAmmonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblAmmonto.setText("jLabel2");
        LblAmmonto.setMaximumSize(new java.awt.Dimension(140, 45));
        LblAmmonto.setMinimumSize(new java.awt.Dimension(140, 45));
        LblAmmonto.setPreferredSize(new java.awt.Dimension(140, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        add(LblAmmonto, gridBagConstraints);

        LblData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblData.setText("jLabel3");
        LblData.setMaximumSize(new java.awt.Dimension(140, 45));
        LblData.setMinimumSize(new java.awt.Dimension(100, 45));
        LblData.setPreferredSize(new java.awt.Dimension(100, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 15);
        add(LblData, gridBagConstraints);

        LblNome.setText("jLabel4");
        LblNome.setMaximumSize(new java.awt.Dimension(180, 45));
        LblNome.setMinimumSize(new java.awt.Dimension(180, 45));
        LblNome.setPreferredSize(new java.awt.Dimension(180, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        add(LblNome, gridBagConstraints);

        LblTipo.setText("jLabel5");
        LblTipo.setMaximumSize(new java.awt.Dimension(180, 45));
        LblTipo.setMinimumSize(new java.awt.Dimension(100, 45));
        LblTipo.setPreferredSize(new java.awt.Dimension(100, 45));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 5, 0);
        add(LblTipo, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAmmonto;
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblTipo;
    // End of variables declaration//GEN-END:variables
}
