/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author matge
 */
public class FrmHome extends javax.swing.JFrame {

    /**
     * Creates new form FrmHome
     */
    public FrmHome() 
    {
        initComponents();
        getContentPane().setBackground(Color.DARK_GRAY);
        this.pack();
        setTitle("Gestore Spese");
        PnlLayer.setLayout(null);
       
        //Bottone Menu
        BtnMenu.setFocusPainted(false);
        BtnMenu.setBorderPainted(false);
        BtnMenu.setContentAreaFilled(false);
        BtnMenu.setOpaque(false);
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/main-menu.png"));
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(img);
        BtnMenu.setIcon(scaledIcon);
        
        //Pannello menu
        menu.setBounds(0, 100, 200, 700);
        menu.setVisible(false);
        PnlLayer.add(menu, Integer.valueOf(3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlFinestra = new javax.swing.JPanel();
        PnlLayer = new javax.swing.JLayeredPane();
        PnlContenuto = new javax.swing.JPanel();
        PnlHeader = new javax.swing.JPanel();
        BtnMenu = new javax.swing.JButton();
        PnlSaldo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlBottomMenu = new javax.swing.JPanel();
        PnlTransazioni = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setMaximumSize(new java.awt.Dimension(420, 1000));
        setMinimumSize(new java.awt.Dimension(420, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(420, 800));
        setResizable(false);

        PnlFinestra.setMaximumSize(new java.awt.Dimension(420, 800));
        PnlFinestra.setMinimumSize(new java.awt.Dimension(420, 800));
        PnlFinestra.setOpaque(false);
        PnlFinestra.setPreferredSize(new java.awt.Dimension(420, 800));

        PnlLayer.setMaximumSize(new java.awt.Dimension(420, 800));
        PnlLayer.setMinimumSize(new java.awt.Dimension(420, 800));
        PnlLayer.setPreferredSize(new java.awt.Dimension(420, 800));

        PnlContenuto.setBackground(java.awt.Color.darkGray);
        PnlContenuto.setMaximumSize(new java.awt.Dimension(420, 800));
        PnlContenuto.setMinimumSize(new java.awt.Dimension(420, 800));
        PnlContenuto.setOpaque(false);
        PnlContenuto.setPreferredSize(new java.awt.Dimension(420, 800));

        PnlHeader.setBackground(new java.awt.Color(51, 51, 51));
        PnlHeader.setMaximumSize(new java.awt.Dimension(420, 100));
        PnlHeader.setMinimumSize(new java.awt.Dimension(420, 100));

        BtnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMenu.setMaximumSize(new java.awt.Dimension(100, 100));
        BtnMenu.setMinimumSize(new java.awt.Dimension(100, 100));
        BtnMenu.setPreferredSize(new java.awt.Dimension(100, 100));
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlHeaderLayout = new javax.swing.GroupLayout(PnlHeader);
        PnlHeader.setLayout(PnlHeaderLayout);
        PnlHeaderLayout.setHorizontalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlHeaderLayout.createSequentialGroup()
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PnlHeaderLayout.setVerticalGroup(
            PnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PnlSaldo.setBackground(java.awt.Color.darkGray);
        PnlSaldo.setMaximumSize(new java.awt.Dimension(420, 200));
        PnlSaldo.setMinimumSize(new java.awt.Dimension(420, 200));
        PnlSaldo.setPreferredSize(new java.awt.Dimension(420, 200));
        PnlSaldo.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0,00€");
        jLabel1.setMaximumSize(new java.awt.Dimension(250, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(250, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 100));
        jLabel1.setRequestFocusEnabled(false);
        PnlSaldo.add(jLabel1, new java.awt.GridBagConstraints());

        PnlBottomMenu.setBackground(new java.awt.Color(255, 255, 0));
        PnlBottomMenu.setMaximumSize(new java.awt.Dimension(420, 100));
        PnlBottomMenu.setMinimumSize(new java.awt.Dimension(420, 100));
        PnlBottomMenu.setPreferredSize(new java.awt.Dimension(420, 100));

        javax.swing.GroupLayout PnlBottomMenuLayout = new javax.swing.GroupLayout(PnlBottomMenu);
        PnlBottomMenu.setLayout(PnlBottomMenuLayout);
        PnlBottomMenuLayout.setHorizontalGroup(
            PnlBottomMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        PnlBottomMenuLayout.setVerticalGroup(
            PnlBottomMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PnlTransazioni.setBackground(java.awt.Color.darkGray);
        PnlTransazioni.setMaximumSize(new java.awt.Dimension(420, 382));
        PnlTransazioni.setMinimumSize(new java.awt.Dimension(420, 382));
        PnlTransazioni.setPreferredSize(new java.awt.Dimension(420, 382));

        javax.swing.GroupLayout PnlTransazioniLayout = new javax.swing.GroupLayout(PnlTransazioni);
        PnlTransazioni.setLayout(PnlTransazioniLayout);
        PnlTransazioniLayout.setHorizontalGroup(
            PnlTransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PnlTransazioniLayout.setVerticalGroup(
            PnlTransazioniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PnlContenutoLayout = new javax.swing.GroupLayout(PnlContenuto);
        PnlContenuto.setLayout(PnlContenutoLayout);
        PnlContenutoLayout.setHorizontalGroup(
            PnlContenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenutoLayout.createSequentialGroup()
                .addGroup(PnlContenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PnlTransazioni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlContenutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PnlBottomMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PnlContenutoLayout.setVerticalGroup(
            PnlContenutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContenutoLayout.createSequentialGroup()
                .addComponent(PnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlTransazioni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlBottomMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PnlLayer.setLayer(PnlContenuto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PnlLayerLayout = new javax.swing.GroupLayout(PnlLayer);
        PnlLayer.setLayout(PnlLayerLayout);
        PnlLayerLayout.setHorizontalGroup(
            PnlLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(PnlLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnlContenuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlLayerLayout.setVerticalGroup(
            PnlLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(PnlLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlLayerLayout.createSequentialGroup()
                    .addComponent(PnlContenuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout PnlFinestraLayout = new javax.swing.GroupLayout(PnlFinestra);
        PnlFinestra.setLayout(PnlFinestraLayout);
        PnlFinestraLayout.setHorizontalGroup(
            PnlFinestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFinestraLayout.createSequentialGroup()
                .addComponent(PnlLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PnlFinestraLayout.setVerticalGroup(
            PnlFinestraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PnlFinestra, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        if(menu.isVisible())
        {
            menu.setVisible(false);
        }
        else
        {
            menu.setVisible(true);
        }
        
    }//GEN-LAST:event_BtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }
    private PnlMenu menu = new PnlMenu(); 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenu;
    private javax.swing.JPanel PnlBottomMenu;
    private javax.swing.JPanel PnlContenuto;
    private javax.swing.JPanel PnlFinestra;
    private javax.swing.JPanel PnlHeader;
    private javax.swing.JLayeredPane PnlLayer;
    private javax.swing.JPanel PnlSaldo;
    private javax.swing.JPanel PnlTransazioni;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
