/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codice;

import componenti.PaletteColori;
import componenti.RoundButton;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author gabriele.balatti
 */
public class frmLogin extends javax.swing.JFrame {

    private final Color COLORE_PLACEHOLDER = Color.LIGHT_GRAY;
    private final Color COLORE_FONT = Color.BLACK;
    private final Color COLORE_ERRORE = Color.RED;
    private final String PLACEHOLDER_USERNAME = "Inserisci nome utente...";

    java.awt.CardLayout cardLayout1 = null;

    public frmLogin() {
        RegistraFont();
        initComponents();
        this.pack();
        URL iconURL = getClass().getResource("/immagini/icona.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        cardLayout1 = (java.awt.CardLayout) getContentPane().getLayout();
        cardLayout1.show(getContentPane(), "Welcome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JPanel();
        gradientPanel1 = new componenti.GradientPanel();
        jPanel1 = new javax.swing.JPanel();
        roundButton1 = new componenti.RoundButton();
        roundButton2 = new componenti.RoundButton();
        jSeparator1 = new javax.swing.JSeparator();
        imageLabel1 = new componenti.ImageLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlRegistrati = new javax.swing.JPanel();
        lblIstruzioni = new javax.swing.JLabel();
        pnlDati = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new componenti.RoundTextField();
        flrSpazio1 = new javax.swing.Box.Filler(new java.awt.Dimension(420, 30), new java.awt.Dimension(420, 30), new java.awt.Dimension(420, 30));
        lblPassword = new javax.swing.JLabel();
        pswPassword = new componenti.RoundPasswordField();
        flrSpazio2 = new javax.swing.Box.Filler(new java.awt.Dimension(420, 30), new java.awt.Dimension(420, 30), new java.awt.Dimension(420, 30));
        lblRipetiPassword = new javax.swing.JLabel();
        pswRipetiPassword = new componenti.RoundPasswordField();
        sprLinea1 = new javax.swing.JSeparator();
        sprLinea2 = new javax.swing.JSeparator();
        imgLogo = new componenti.ImageLabel();
        grdGradiente = new componenti.GradientPanel();
        pnlBottoni = new javax.swing.JPanel();
        btnRegistrati = new componenti.RoundButton();
        btnAnnulla = new componenti.RoundButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartBudget");
        setMaximumSize(new java.awt.Dimension(420, 800));
        setMinimumSize(new java.awt.Dimension(420, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlWelcome.setBackground(java.awt.Color.white);
        pnlWelcome.setMaximumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setMinimumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setPreferredSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setBackground(java.awt.Color.white);
        gradientPanel1.setColore1(java.awt.Color.white);
        gradientPanel1.setColore2(PaletteColori.VERDE);
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 40, 20));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        roundButton1.setForeground(PaletteColori.BLU);
        roundButton1.setText("Registrati");
        roundButton1.setBorderPainted(true);
        roundButton1.setColoreBordo(java.awt.Color.white);
        roundButton1.setColoreHover(PaletteColori.BLU);
        roundButton1.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundButton1.setRaggio(40);
        roundButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton1MouseExited(evt);
            }
        });
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundButton1);

        roundButton2.setForeground(PaletteColori.BLU);
        roundButton2.setText("Login");
        roundButton2.setColoreBordo(java.awt.Color.white);
        roundButton2.setColoreHover(PaletteColori.BLU);
        roundButton2.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton2.setRaggio(40);
        roundButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton2MouseExited(evt);
            }
        });
        roundButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(roundButton2);

        gradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 170));

        pnlWelcome.add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 400));

        jSeparator1.setForeground(PaletteColori.BLU);
        pnlWelcome.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 40));

        imageLabel1.setImmagine("/immagini/logo.png");
        pnlWelcome.add(imageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 480, 360));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 40));
        jLabel2.setForeground(new java.awt.Color(25, 45, 98));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Benvenuto!");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 420, 40));

        jLabel3.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 16)
        );
        jLabel3.setForeground(new java.awt.Color(25, 45, 98));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Effettua il login o registrati");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 420, -1));

        getContentPane().add(pnlWelcome, "Welcome");

        pnlRegistrati.setBackground(java.awt.Color.white);
        pnlRegistrati.setMaximumSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setMinimumSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setPreferredSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIstruzioni.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 15));
        lblIstruzioni.setForeground(new java.awt.Color(25, 45, 98));
        lblIstruzioni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIstruzioni.setText("Inserisci i dati per continuare");
        lblIstruzioni.setAlignmentX(0.5F);
        lblIstruzioni.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlRegistrati.add(lblIstruzioni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 420, 40));

        pnlDati.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 20));
        pnlDati.setOpaque(false);
        pnlDati.setLayout(new javax.swing.BoxLayout(pnlDati, javax.swing.BoxLayout.PAGE_AXIS));

        lblUsername.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 15)
        );
        lblUsername.setForeground(new java.awt.Color(25, 45, 98));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        lblUsername.setAlignmentX(0.5F);
        lblUsername.setMaximumSize(new java.awt.Dimension(340, 30));
        lblUsername.setMinimumSize(new java.awt.Dimension(340, 30));
        lblUsername.setPreferredSize(new java.awt.Dimension(340, 30));
        pnlDati.add(lblUsername);

        txtUsername.setText("Inserisci nome utente...");
        txtUsername.setColoreBordo(PaletteColori.BLU);
        txtUsername.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 16)
        );
        txtUsername.setMaximumSize(new java.awt.Dimension(340, 60));
        txtUsername.setMinimumSize(new java.awt.Dimension(340, 60));
        txtUsername.setPreferredSize(new java.awt.Dimension(340, 60));
        txtUsername.setRaggio(40);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        pnlDati.add(txtUsername);
        pnlDati.add(flrSpazio1);

        lblPassword.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 15)
        );
        lblPassword.setForeground(new java.awt.Color(25, 45, 98));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        lblPassword.setAlignmentX(0.5F);
        lblPassword.setMaximumSize(new java.awt.Dimension(340, 30));
        lblPassword.setMinimumSize(new java.awt.Dimension(340, 30));
        lblPassword.setPreferredSize(new java.awt.Dimension(340, 30));
        pnlDati.add(lblPassword);

        pswPassword.setMaximumSize(new java.awt.Dimension(340, 60));
        pswPassword.setMinimumSize(new java.awt.Dimension(340, 60));
        pswPassword.setPreferredSize(new java.awt.Dimension(340, 60));
        pswPassword.setRaggio(40);
        pnlDati.add(pswPassword);
        pnlDati.add(flrSpazio2);

        lblRipetiPassword.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 15)
        );
        lblRipetiPassword.setForeground(new java.awt.Color(25, 45, 98));
        lblRipetiPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRipetiPassword.setText("Ripeti password");
        lblRipetiPassword.setAlignmentX(0.5F);
        lblRipetiPassword.setMaximumSize(new java.awt.Dimension(340, 30));
        lblRipetiPassword.setMinimumSize(new java.awt.Dimension(340, 30));
        lblRipetiPassword.setPreferredSize(new java.awt.Dimension(340, 30));
        pnlDati.add(lblRipetiPassword);

        pswRipetiPassword.setMaximumSize(new java.awt.Dimension(340, 60));
        pswRipetiPassword.setMinimumSize(new java.awt.Dimension(340, 60));
        pswRipetiPassword.setPreferredSize(new java.awt.Dimension(340, 60));
        pswRipetiPassword.setRaggio(40);
        pnlDati.add(pswRipetiPassword);

        pnlRegistrati.add(pnlDati, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 420, 350));

        sprLinea1.setForeground(PaletteColori.BLU);
        pnlRegistrati.add(sprLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 330, 20));

        sprLinea2.setForeground(PaletteColori.BLU);
        pnlRegistrati.add(sprLinea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 330, 40));

        imgLogo.setImmagine("/immagini/logo.png");
        pnlRegistrati.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 480, 210));

        grdGradiente.setBackground(java.awt.Color.white);
        grdGradiente.setColore1(java.awt.Color.white);
        grdGradiente.setColore2(PaletteColori.VERDE);
        grdGradiente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBottoni.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 40, 20));
        pnlBottoni.setOpaque(false);
        pnlBottoni.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        btnRegistrati.setForeground(PaletteColori.BLU);
        btnRegistrati.setText("Registrati");
        btnRegistrati.setBorderPainted(true);
        btnRegistrati.setColoreBordo(java.awt.Color.white);
        btnRegistrati.setColoreHover(PaletteColori.BLU);
        btnRegistrati.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        btnRegistrati.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrati.setRaggio(40);
        pnlBottoni.add(btnRegistrati);

        btnAnnulla.setForeground(PaletteColori.BLU);
        btnAnnulla.setText("Anulla");
        btnAnnulla.setColoreBordo(java.awt.Color.white);
        btnAnnulla.setColoreHover(PaletteColori.BLU);
        btnAnnulla.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        btnAnnulla.setRaggio(40);
        pnlBottoni.add(btnAnnulla);

        grdGradiente.add(pnlBottoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 170));

        pnlRegistrati.add(grdGradiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 400));

        getContentPane().add(pnlRegistrati, "Registrati");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton2MouseExited
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(Color.WHITE);
        bottone.setForeground(PaletteColori.BLU);
    }//GEN-LAST:event_roundButton2MouseExited

    private void roundButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton2MouseEntered
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(PaletteColori.BLU);
        bottone.setForeground(Color.WHITE);
    }//GEN-LAST:event_roundButton2MouseEntered

    private void roundButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton2ActionPerformed

    private void roundButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton1MouseExited
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(Color.WHITE);
        bottone.setForeground(PaletteColori.BLU);
    }//GEN-LAST:event_roundButton1MouseExited

    private void roundButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton1MouseEntered
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(PaletteColori.BLU);
        bottone.setForeground(Color.WHITE);
    }//GEN-LAST:event_roundButton1MouseEntered

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        cardLayout1.show(getContentPane(), "Registrati");
    }//GEN-LAST:event_roundButton1ActionPerformed

    //GESTIONE DEL PANNELLO PER LA REGISTRAZIONE

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals(PLACEHOLDER_USERNAME)) {
            txtUsername.setText("");
            txtUsername.setForeground(COLORE_FONT);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setText(PLACEHOLDER_USERNAME);
            txtUsername.setForeground(COLORE_PLACEHOLDER);
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        ControlloUsername();
    }//GEN-LAST:event_txtUsernameKeyReleased

    public void ControlloUsername() {
        String username = txtUsername.getText();
        if (username.equals(PLACEHOLDER_USERNAME) || username.isEmpty()) {
            UsernameValido();
            return;
        } else if (username.contains(" ")) {
            UsernameInvalido("Uno username non può contenere spazi");
        } else if (username.length() <= 3) {
            UsernameInvalido("Uno username deve avere almeno 3 caratteri");
        } else if (usernameEsistente(username)) {
            UsernameInvalido("Username già esistente");
        } else {
            UsernameValido();
        }
    }

    public void UsernameValido() {
        txtUsername.setColoreBordo(PaletteColori.BLU);
        lblUsername.setForeground(PaletteColori.BLU);
        lblUsername.setText("Username");
    }

    public void UsernameInvalido(String messaggio) {
        txtUsername.setColoreBordo(COLORE_ERRORE);
        lblUsername.setForeground(COLORE_ERRORE);
        lblUsername.setText("Username - " + messaggio);

    }

    public ArrayList<Utente> getListaUtenti() {
        try {
            FileInputStream file = new FileInputStream("Utenti.dat");
            ObjectInputStream input = new ObjectInputStream(file);
            return (ArrayList<Utente>) input.readObject();
        } catch (Exception e) {
            return new java.util.ArrayList<>();
        }

    }

    public Utente getUtente(String username) {
        username = username.toLowerCase();
        ArrayList<Utente> utenti = getListaUtenti();
        for (int i = 0; i < utenti.size(); i++) {
            Utente temp = utenti.get(i); 
            if (temp.getUsername().toLowerCase().equals(username)) {
                return temp;
            }
        }
        return null;
    }

    public boolean usernameEsistente (String username) {
        return getUtente(username) != null;
    }
    
    public void RegistraFont() {
        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-Regular.ttf")));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-Bold.ttf")));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-SemiBold.ttf")));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componenti.RoundButton btnAnnulla;
    private componenti.RoundButton btnRegistrati;
    private javax.swing.Box.Filler flrSpazio1;
    private javax.swing.Box.Filler flrSpazio2;
    private componenti.GradientPanel gradientPanel1;
    private componenti.GradientPanel grdGradiente;
    private componenti.ImageLabel imageLabel1;
    private componenti.ImageLabel imgLogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIstruzioni;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRipetiPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlBottoni;
    private javax.swing.JPanel pnlDati;
    private javax.swing.JPanel pnlRegistrati;
    private javax.swing.JPanel pnlWelcome;
    private componenti.RoundPasswordField pswPassword;
    private componenti.RoundPasswordField pswRipetiPassword;
    private componenti.RoundButton roundButton1;
    private componenti.RoundButton roundButton2;
    private javax.swing.JSeparator sprLinea1;
    private javax.swing.JSeparator sprLinea2;
    private componenti.RoundTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
