/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package balatti_geronimi_javagui;

import java.awt.Font;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author gabriele.balatti
 */
public class frmProva extends javax.swing.JFrame {

    /**
     * Creates new form frmProva
     */
    public frmProva() {
        initComponents();
        this.pack();
        RegistraFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JPanel();
        gradientPanel1 = new balatti_geronimi_javagui.GradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roundTextField2 = new balatti_geronimi_javagui.RoundTextField();
        imageLabel1 = new balatti_geronimi_javagui.ImageLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 800));
        setMinimumSize(new java.awt.Dimension(420, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlWelcome.setBackground(java.awt.Color.white);
        pnlWelcome.setMaximumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setMinimumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setPreferredSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setBackground(java.awt.Color.white);
        gradientPanel1.setColore1(java.awt.Color.white);
        gradientPanel1.setColore2(PaletteColori.VERDE);

        javax.swing.GroupLayout gradientPanel1Layout = new javax.swing.GroupLayout(gradientPanel1);
        gradientPanel1.setLayout(gradientPanel1Layout);
        gradientPanel1Layout.setHorizontalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        gradientPanel1Layout.setVerticalGroup(
            gradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pnlWelcome.add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 400));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 24));
        jLabel2.setForeground(new java.awt.Color(25, 45, 98));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Benvenuto!");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 420, 40));

        jLabel3.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 14)
        );
        jLabel3.setForeground(new java.awt.Color(25, 45, 98));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Effettua il login o registrati");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 420, -1));

        roundTextField2.setEditable(false);
        roundTextField2.setBackground(java.awt.Color.white);
        roundTextField2.setColoreBordo(new java.awt.Color(25, 45, 98));
        roundTextField2.setDisabledTextColor(new java.awt.Color(25, 45, 98));
        roundTextField2.setFocusable(false);
        roundTextField2.setRaggio(30);
        pnlWelcome.add(roundTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 260, 70));

        imageLabel1.setImmagine("C:\\Users\\gabri\\OneDrive\\Documenti\\NetBeansProjects\\Balatti_Geronimi_JavaGUI\\src\\immagini\\logo.png");
        pnlWelcome.add(imageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 480, 360));

        getContentPane().add(pnlWelcome, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void RegistraFont() {
    try {
    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
    ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, 
        getClass().getResourceAsStream("/fonts/Montserrat-Regular.ttf")));
    ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, 
        getClass().getResourceAsStream("/fonts/Montserrat-Bold.ttf")));
    ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, 
        getClass().getResourceAsStream("/fonts/Montserrat-SemiBold.ttf")));
} catch (Exception e) {
    e.printStackTrace();
}
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProva().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private balatti_geronimi_javagui.GradientPanel gradientPanel1;
    private balatti_geronimi_javagui.ImageLabel imageLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlWelcome;
    private balatti_geronimi_javagui.RoundTextField roundTextField2;
    // End of variables declaration//GEN-END:variables
}
