/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package balatti_geronimi_javagui;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author gabriele.balatti
 */
public class frmProva extends javax.swing.JFrame {

    java.awt.CardLayout cardLayout1 = null;
    
    public frmProva() {
        initComponents();
        this.pack();
        RegistraFont();
        URL iconURL = getClass().getResource("/immagini/icona.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        cardLayout1 = (java.awt.CardLayout) getContentPane().getLayout();
        cardLayout1.show(getContentPane(), "Welcome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JPanel();
        gradientPanel1 = new balatti_geronimi_javagui.GradientPanel();
        jPanel1 = new javax.swing.JPanel();
        roundButton1 = new balatti_geronimi_javagui.RoundButton();
        roundButton2 = new balatti_geronimi_javagui.RoundButton();
        jSeparator1 = new javax.swing.JSeparator();
        imageLabel1 = new balatti_geronimi_javagui.ImageLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlRegistrati = new javax.swing.JPanel();
        gradientPanel2 = new balatti_geronimi_javagui.GradientPanel();
        jPanel2 = new javax.swing.JPanel();
        roundButton3 = new balatti_geronimi_javagui.RoundButton();
        roundButton4 = new balatti_geronimi_javagui.RoundButton();
        jSeparator2 = new javax.swing.JSeparator();
        imageLabel2 = new balatti_geronimi_javagui.ImageLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 800));
        setMinimumSize(new java.awt.Dimension(420, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlWelcome.setBackground(java.awt.Color.white);
        pnlWelcome.setMaximumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setMinimumSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setPreferredSize(new java.awt.Dimension(420, 800));
        pnlWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel1.setBackground(java.awt.Color.white);
        gradientPanel1.setColore1(java.awt.Color.white);
        gradientPanel1.setColore2(PaletteColori.VERDE);
        gradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 40, 20));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        roundButton1.setForeground(PaletteColori.BLU);
        roundButton1.setText("Registrati");
        roundButton1.setBorderPainted(true);
        roundButton1.setColoreBordo(java.awt.Color.white);
        roundButton1.setColoreHover(PaletteColori.BLU);
        roundButton1.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundButton1.setRaggio(40);
        roundButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton1MouseExited(evt);
            }
        });
        roundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundButton1);

        roundButton2.setForeground(PaletteColori.BLU);
        roundButton2.setText("Login");
        roundButton2.setColoreBordo(java.awt.Color.white);
        roundButton2.setColoreHover(PaletteColori.BLU);
        roundButton2.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton2.setRaggio(40);
        roundButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton2MouseExited(evt);
            }
        });
        roundButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(roundButton2);

        gradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 170));

        pnlWelcome.add(gradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 400));

        jSeparator1.setForeground(PaletteColori.BLU);
        pnlWelcome.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 40));

        imageLabel1.setImmagine("/immagini/logo.png");
        pnlWelcome.add(imageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 480, 360));

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 40));
        jLabel2.setForeground(new java.awt.Color(25, 45, 98));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Benvenuto!");
        jLabel2.setAlignmentX(0.5F);
        jLabel2.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 420, 40));

        jLabel3.setFont(new java.awt.Font("Montserrat", java.awt.Font.PLAIN, 16)
        );
        jLabel3.setForeground(new java.awt.Color(25, 45, 98));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Effettua il login o registrati");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 50));
        pnlWelcome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 420, -1));

        getContentPane().add(pnlWelcome, "Welcome");

        pnlRegistrati.setBackground(java.awt.Color.white);
        pnlRegistrati.setMaximumSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setMinimumSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setPreferredSize(new java.awt.Dimension(420, 800));
        pnlRegistrati.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradientPanel2.setBackground(java.awt.Color.white);
        gradientPanel2.setColore1(java.awt.Color.white);
        gradientPanel2.setColore2(PaletteColori.VERDE);
        gradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 40, 20));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 20));

        roundButton3.setForeground(PaletteColori.BLU);
        roundButton3.setText("Registrati");
        roundButton3.setBorderPainted(true);
        roundButton3.setColoreBordo(java.awt.Color.white);
        roundButton3.setColoreHover(PaletteColori.BLU);
        roundButton3.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundButton3.setRaggio(40);
        roundButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton3MouseExited(evt);
            }
        });
        roundButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(roundButton3);

        roundButton4.setForeground(PaletteColori.BLU);
        roundButton4.setText("Login");
        roundButton4.setColoreBordo(java.awt.Color.white);
        roundButton4.setColoreHover(PaletteColori.BLU);
        roundButton4.setFont(new java.awt.Font("Montserrat SemiBold", java.awt.Font.PLAIN, 20)
        );
        roundButton4.setRaggio(40);
        roundButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roundButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roundButton4MouseExited(evt);
            }
        });
        roundButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(roundButton4);

        gradientPanel2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 170));

        pnlRegistrati.add(gradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 420, 400));

        jSeparator2.setForeground(PaletteColori.BLU);
        pnlRegistrati.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 330, 40));

        imageLabel2.setImmagine("/immagini/logo.png");
        pnlRegistrati.add(imageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 480, 360));

        getContentPane().add(pnlRegistrati, "Registrati");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton1ActionPerformed
        cardLayout1.show(getContentPane(), "Registrati");
    }//GEN-LAST:event_roundButton1ActionPerformed

    private void roundButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton1MouseEntered
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(PaletteColori.BLU);
        bottone.setForeground(Color.WHITE);
    }//GEN-LAST:event_roundButton1MouseEntered

    private void roundButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton1MouseExited
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(Color.WHITE);
        bottone.setForeground(PaletteColori.BLU);
    }//GEN-LAST:event_roundButton1MouseExited

    private void roundButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton2ActionPerformed

    private void roundButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton2MouseEntered
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(PaletteColori.BLU);
        bottone.setForeground(Color.WHITE);
    }//GEN-LAST:event_roundButton2MouseEntered

    private void roundButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton2MouseExited
        RoundButton bottone = (RoundButton) evt.getSource();
        bottone.setColoreBordo(Color.WHITE);
        bottone.setForeground(PaletteColori.BLU);
    }//GEN-LAST:event_roundButton2MouseExited

    private void roundButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton3MouseEntered

    private void roundButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton3MouseExited

    private void roundButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton3ActionPerformed

    private void roundButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton4MouseEntered

    private void roundButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roundButton4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton4MouseExited

    private void roundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roundButton4ActionPerformed

    public void RegistraFont() {
        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-Regular.ttf")));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-Bold.ttf")));
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/fonts/Montserrat-SemiBold.ttf")));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProva().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private balatti_geronimi_javagui.GradientPanel gradientPanel1;
    private balatti_geronimi_javagui.GradientPanel gradientPanel2;
    private balatti_geronimi_javagui.ImageLabel imageLabel1;
    private balatti_geronimi_javagui.ImageLabel imageLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlRegistrati;
    private javax.swing.JPanel pnlWelcome;
    private balatti_geronimi_javagui.RoundButton roundButton1;
    private balatti_geronimi_javagui.RoundButton roundButton2;
    private balatti_geronimi_javagui.RoundButton roundButton3;
    private balatti_geronimi_javagui.RoundButton roundButton4;
    // End of variables declaration//GEN-END:variables
}
